### ISSUE TITLE
Service Titles Incorrect. 

### ISSUE THREAD

**Issue by Th0mX** [danfoy/setupgenerator#26]
The names for the types of setups has changed. 
'Walk Out Working' is now 'Computer Set-Up'
'Setup and Personalise' is now 'Computer Set-Up & Personalise'
'Setup and Showhow' is now 'Computer Set-Up, Personalise plus In-Store Tutorial'

These should be adjusted accordingly

**Comment by Th0mX** [comment]
or maybe reduce it to
Computer Set-Up
Set-Up & Personalise
Set-Up & Personalise + Tutorial 
... because spacing and stuff

**Comment by Th0mX** [comment]
Leave a comment

**Comment by danfoy** [comment]
r/oldpeoplefacebook tier comment there, 8/8

**Comment by danfoy** [comment]
As discussed, I think I'll sit on this for a bit until people get used to the distinction between `setup` and `setup and personalise`. And `setup and personalise + tutorial` is wordy af.

**Comment by Th0mX** [comment]
I didn't comment when I reopened the issue after closing it. That's just the default.

**Comment by danfoy** [comment]
Decided the time has come to fix this.
