### ISSUE TITLE
Wording Change

### ISSUE THREAD

**Issue by Th0mX** [danfoy/setupgenerator#37]
Petty semantics issue. On the printout, when it wants us to create a new Microsoft Account, it shows as:

"Add New Microsoft Account"

Maybe this could be changed to:

"Create New Microsoft Account"

Insignificant, I know, but it's /r/mildlyinfuriating/ to me.

**Comment by Th0mX** [comment]
It's even more mildly infuriating when the customer has an existing email account so it says "Add Existing Account".

It's just a way to make it appear different

**Comment by danfoy** [comment]
It already appears like this on the creation end, it's just the printout that has this wording. Having said that, petty semantics issue noted and fixed ;)
